version: 2.1
orbs:
  python: circleci/python@2.1.1
  win: circleci/windows@5.0
  macos: circleci/macos@2
jobs:
  format:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Format Checking
         command: poetry run make format-check
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Run tests
         command: poetry run pytest
  create-cli-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build Windows CLI
          shell: cmd.exe
          command: |
            curl -sSL https://install.python-poetry.org | python - && ..\AppData\Roaming\Python\Scripts\poetry install && ..\AppData\Roaming\Python\Scripts\poetry run pyinstaller src/cli.py --onefile --name dfm && 7z a ./cli-windows.zip ./dist/
      - store_artifacts:
          path: cli-windows.zip
  create-cli-linux:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
          name: Create CLI
          command: |
            poetry run pyinstaller src/cli.py --onefile --name dfm
            zip -r cli-linux.zip dist/dfm 
      - store_artifacts:
          path: cli-linux.zip
  create-cli-mac:
    macos:
      xcode: 13.4.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build Mac CLI
          command: |
            brew install python@3.11
            curl -sSL https://install.python-poetry.org | python3 -
            $HOME/.local/bin/poetry install
            $HOME/.local/bin/poetry run pyinstaller src/cli.py --onefile --name dfm
            zip -r cli-mac.zip dist/dfm 
      - store_artifacts:
          path: cli-mac.zip

workflows:
  lint-and-test:
    jobs:
      - format
      - test
  create-cli:
    jobs:
      - create-cli-linux:
          filters:
            branches:
              only: main
      - create-cli-windows:
          filters:
            branches:
              only: main
      - create-cli-mac:
          filters:
            branches:
              only: main