version: 2.1
orbs:
  python: circleci/python@2.1.1
  win: circleci/windows@5.0
  macos: circleci/macos@2

commands:
  unit-test:
    description: "Runs the generic pytest testing command"
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Run tests
         command: poetry run pytest

jobs:
  format:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Format Checking
         command: poetry run make format-check
  test-311:
    docker:
      - image: cimg/python:3.11
    steps:
      - unit-test
  test-310:
    docker:
      - image: cimg/python:3.10
    steps:
      - unit-test
  test-39:
    docker:
      - image: cimg/python:3.9
    steps:
      - unit-test
  test-38:
    docker:
      - image: cimg/python:3.8
    steps:
      - unit-test

  create-cli-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build Windows CLI
          shell: cmd.exe
          command: |
            choco install pyenv-win -y --force && refreshenv && pyenv install 3.11.0b4 && pyenv global 3.11.0b4 && pyenv shell 3.11.0b4 && curl -sSL https://install.python-poetry.org | python3 - && ..\AppData\Roaming\Python\Scripts\poetry install && ..\AppData\Roaming\Python\Scripts\poetry run pyinstaller src/dfm/cli.py --onefile --name dfm && 7z a ./cli-windows.zip ./dist/
      - store_artifacts:
          path: cli-windows.zip
  create-cli-linux:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
          name: Create CLI
          command: |
            poetry run pyinstaller src/dfm/cli.py --onefile --name dfm
            zip -r cli-linux.zip dist/dfm 
      - store_artifacts:
          path: cli-linux.zip
  create-cli-mac:
    macos:
      xcode: 13.4.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build Mac CLI
          command: |
            brew install python@3.11
            curl -sSL https://install.python-poetry.org | python3.11 -
            $HOME/.local/bin/poetry install
            $HOME/.local/bin/poetry run pyinstaller src/dfm/cli.py --onefile --name dfm
            zip -r cli-mac.zip dist/dfm 
      - store_artifacts:
          path: cli-mac.zip

workflows:
  lint-and-test:
    jobs:
      - format
      - test-311
  regression-test:
    jobs:
      - test-38
      - test-39
      - test-310
  create-cli:
    jobs:
      - create-cli-linux:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - create-cli-windows:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - create-cli-mac:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/