version: 2.1
orbs:
  python: circleci/python@2.1.1
  win: circleci/windows@5.0
jobs:
  format:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Format Checking
         command: poetry run make format-check
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Run tests
         command: poetry run pytest
  create-cli-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build Windows CLI
          shell: cmd.exe
          command: |
            curl -sSL https://install.python-poetry.org | python - && C:\Users\circleci.PACKER-631B74C9\AppData\Roaming\Python\Scripts\poetry install && C:\Users\circleci.PACKER-631B74C9\AppData\Roaming\Python\Scripts\poetry run pyinstaller src/cli.py --onefile --name dfm
      - store_artifacts:
          path: dist/dfm.exe
          destination: cli-windows
  create-cli-unix:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
          name: Create CLI
          command: poetry run pyinstaller src/cli.py --onefile --name dfm
      - store_artifacts:
          path: dist/dfm
          destination: cli-unix

workflows:
  lint-and-test:
    jobs:
      - format
      - test
  create-cli:
    jobs:
      - create-cli-unix:
        filters:
          branches:
            only: main
      - create-cli-windows:
        filters:
          branches:
            only: main