version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  format:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Format Checking
         command: poetry run make format-check
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: poetry
      - run:
         name: Run tests
         command: poetry run pytest
workflows:
  lint-and-test:
    jobs:
      - format
      - test
